#!/bin/bash

cd ../
# python -m experiments.exp_001 -m -c "First Submit"
# python -m experiments.exp_002 -m -c "legacy_seresnext50_32x4d"
# python -m experiments.exp_003 -m -c "th=0.7 -> 0.65"
# python -m experiments.exp_004 -m -c "use secondary_labels"
# python -m experiments.exp_005 -m -c "mixup"
# python -m experiments.exp_006 -m -c "train only first 80% audio"
# python -m experiments.exp_007 -m -c "add rain noise"
# python -m experiments.exp_008 -m -c "add post-process"
# python -m experiments.exp_009 -m -c "add bus noise"
# python -m experiments.exp_010 -m -c "efficientnet_b0"
# python -m experiments.exp_011 -m -c "efficientnet_b3"
# python -m experiments.exp_012 -m -c "train only first 5[sec] and last 5[sec]"
# python -m experiments.exp_013 -m -c "3tta random shift 2.5[sec]"
# python -m experiments.exp_014 -m -c "efficientnet_b4"
# python -m experiments.exp_015 -m -c "legacy_seresnext50_32x4d, epoch=60"
# python -m experiments.exp_016 -m -c "resnest50d"
# python -m experiments.exp_017 -m -c "resnest50d_4s2x40d"
# python -m experiments.exp_018 -m -c "legacy_seresnext50_32x4d, nocall noise: 0.5 ~ 1.01"
# python -m experiments.exp_019 -m -c "legacy_seresnext50_32x4d, nocall noise: 0.25 ~ 1.01"
# python -m experiments.exp_020 -m -c "use latitude and longitude"
# python -m experiments.exp_021 -m -c "use latitude and longitude, modified"
# python -m experiments.exp_022 -m -c "use latitude and longitude, drop non_test_birds_idx"
# python -m experiments.exp_023 -m -c "use latitude and longitude, drop non_test_region_idx"
# python -m experiments.exp_024 -m -c "use distance from mean position"
# python -m experiments.exp_025 -m -c "use distance from min position"
# python -m experiments.exp_026 -m -c "use audiomentations"
# python -m experiments.exp_027 -m -c "bus_noise and Gain"
# python -m experiments.exp_028 -m -c "torchlibrosa"
python -m experiments.exp_029 -m -c "AddGaussianNoise"
python -m experiments.exp_030 -m -c "AddGaussianNoise, add bus noise"